version = 1

test_patterns = ["test/"]

exclude_patterns = [
  "src/Infrastructure/Migrations/**",
  "**/bin/**",
  "**/obj/**",
  "**/*.Designer.cs",
  "**/AssemblyInfo.cs",
  "test/**/*",  # Excluir tests del análisis principal
  "**/TestResults/*"
]

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
