name: DeepSource .NET 8 Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache dependencias NuGet
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restaurar dependencias usando solución
      run: dotnet restore TemplateNetBase.sln

    - name: Build solución completa
      run: dotnet build TemplateNetBase.sln --configuration Release --no-restore

    - name: Ejecutar tests
      run: dotnet test TemplateNetBase.sln --configuration Release --no-build --verbosity normal

    - name: Publicar resultados de tests
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test/**/TestResults/*.trx

  deepsource-analysis:
    name: DeepSource Code Analysis
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Ejecutar análisis DeepSource
      uses: deepsource-io/action@v1
      with:
        deepsource-dsn: ${{ secrets.DEEPSOURCE_DSN }}
        fail-on-errors: true

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Verificar formato de código
      run: |
        dotnet format TemplateNetBase.sln --verify-no-changes --severity warn

    - name: Verificar paquetes vulnerables
      run: |
        dotnet list TemplateNetBase.sln package --vulnerable --include-transitive