name: DeepSource .NET 8 Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        # Importante para análisis preciso en PRs
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restaurar dependencias
      run: dotnet restore TemplateNetBase.sln

    - name: Build solución
      run: dotnet build TemplateNetBase.sln --configuration Release --no-restore

    - name: Ejecutar tests
      run: dotnet test TemplateNetBase.sln --configuration Release --no-build --verbosity normal

  deepsource-analysis:
    name: DeepSource Code Analysis
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Instalar CLI de DeepSource
      run: curl https://deepsource.io/cli | sh

    - name: Ejecutar análisis DeepSource
      run: ./bin/deepsource analyze
      env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}